### ISSUE TITLE
TODO before publication

### ISSUE THREAD

**Issue by BERENZ** [OJALAB/paper-job-ads-classifier#1]
What to do before the submission of the paper

- [x] clean the repository and check reproducibility
- [x] create excel file `models-accuracy.xlsx` with all results
- [x] link to tutorial on Google Colab notebooks
- [x] add link to models (repod)
